### ISSUE TITLE
Custom styling for HYPForms

### ISSUE THREAD

**Issue by andrewgubanov** [hyperoslo/Form#198]
Please consider implementing possibility to customize style, colors, etc in the HYPForms, because hadrcoded style restricts the usage of this nice library.

**Comment by zenangst** [comment]
Consider it on our todo list :-)

**Comment by andrewgubanov** [comment]
:+1:

**Comment by NSElvis** [comment]
@andrewgubanov :heart:

**Comment by NSElvis** [comment]
We have 

```objc
typedef void (^HYPFieldConfigureCellBlock)(id cell, NSIndexPath *indexPath, HYPFormField *field);
```

It's a configuration block that gets called when the cells get called for usage (reusage), if it's not implemented it only does [this].(https://github.com/hyperoslo/HYPForms/blob/master/Source/HYPFormsCollectionViewDataSource.m#L166)

The idea is that you in this configuration block can change the color of the cell background, cell title label and so on.

You can do the same thing with the `headerConfigurationBlock`.

This might be an overkill since styling should be applied only on initialization.

Other idea could be providing a "THEMEPROVIDER"

Yeah.

**Comment by andrewgubanov** [comment]
@NSElvis I was more thinking about HYPFormBackgroundView which is not possible to style for now.
But anyways, ThemeProvider/ThemeStyler would be the best solution as it could style propper views/cells only when those are instantiated.

**Comment by NSElvis** [comment]
@andrewgubanov maybe considering `UIAppearance` is a good idea too

**Comment by andrewgubanov** [comment]
@NSElvis depends on how much you want to allow user to customize your interface. UIAppearance is good for "coloring" already styled UI. But if you want your users to  be able to actually style the UI, then you need smth like ThemeProvier, etc. It is like if I want to have my backgroundview in a shape of a peer for example. In this case UIAppearance won't help much :)

**Comment by NSElvis** [comment]
I tried UIAppearance with `FORMTextField`, works pretty good.

```objc
[[FORMTextField appearance] setTextColor:[UIColor redColor]];
[[FORMTextField appearance] setBackgroundColor:[UIColor yellowColor]];
```

There are two caveats, the first one is that we need to avoid setting the colors [the way we've been doing it](https://github.com/hyperoslo/Form/blob/b1a542d042a45a9a3056fb8969b5704e51fda1f4/Source/Cells/Views/FORMTextField.m#L98), otherwise appearance doesn't work.

The second one is that I haven't figured out how to style a CALayer using UIAppearance

**Comment by andrewgubanov** [comment]
@NSElvis 
>There are two caveats, the first one is that we need to avoid setting the colors the way we've been doing it, otherwise UIAppearance doesn't work.

This is expected behaviour of the way UIAppearane works. You can read more info [here] (http://useyourloaf.com/blog/2012/08/24/using-appearance-proxy-to-style-apps.html).

There is also no way to style CALayer as it does not conform to UIAppearance. For this reason I have implemented my own DMAppearance you can check out. Then in your custom CALayer you conform to UIAppearance protocol and in +[MYCALayer appearance] return DMAppearanceRecord instance.
Another option is to not give access to underlying CALayer of your UIView. You simply declare properties cornerRadius, borderColor, etc with UI_APPEARANCE_SELECTOR in your UIView subclass, and in setters set those values into self.layer.
Keep in mind that if you want to provide default styling via UIAppearance flow in your custom views, you should do this in +load or +initialize methods depends on how much you do not care about the memory footpring of your app :) I personally do this in +initialize

**Comment by NSElvis** [comment]
@andrewgubanov I was looking into this approach and I like it a lot! :)

> You simply declare properties cornerRadius, borderColor, etc with UI_APPEARANCE_SELECTOR in your UIView subclass, and in setters set those values into self.layer.
