### ISSUE TITLE
Accessing each textfield and saving data

### ISSUE THREAD

**Issue by RyanKim01** [hyperoslo/Form#489]
Hi
I came across this awesome api and just loving this.
I am sorry if my issues are a duplicate.

I was wondering if there is a way to access individual textfield in the Form. Let's say there is a field "Age" and I input "10". I want to access this data so I can transfer this data to other place. In other words, I would like to access individual textfield and get value from them. 

One more thing about exporting the data. When user finish putting inputs, where are the data being saved? Is there a way to export the data to third party library? And I wonder if the data will be only saved in JSON file. Does Form support other format of data ?

Thank you in advance

**Comment by 3lvis** [comment]
Hi @RyanKim01,

Almost everything in Form is done through the FORMDataSource, you can find more setup information on the several examples that we have. Try this command in your terminal to get them:

```
pod try Form
```

I added a FAQ section with answers to some of the questions that you have asked. I hope this helps you. Otherwise let me know and I'll reopen this issue.

https://github.com/hyperoslo/Form#faq

Have a nice day :sparkles:

**Comment by RyanKim01** [comment]
@3lvis, thank you so much for your response. I wonder one more thing that if there's any way I can save data in JSON format instead of dictionary format. I checked out values in datasource.values and they were in a dictionary format.

**Comment by 3lvis** [comment]
@RyanKim01 Not out of the box. You might find a good way to convert a dictionary into a JSON :) 

Best,

**Comment by RyanKim01** [comment]
Thank you Elvis. Appreciate your time and answer!

**Comment by 3lvis** [comment]
@RyanKim01 my pleasure :bouquet:
