### ISSUE TITLE
In demo when I change some project like basic to universal it looks like on image I attached , and this looks really bad.

### ISSUE THREAD

**Issue by rene-dohan** [hyperoslo/Form#526]
So iPhone is not supported ?

![simulator screen shot 23 jun 2016 13 24 29](https://cloud.githubusercontent.com/assets/923610/16314949/da6e2d3c-3945-11e6-8215-5487e2db337d.png)

**Comment by 3lvis** [comment]
@rene-dohan You have to specify and iPhone specific JSON file. Something [like this](https://github.com/hyperoslo/Form/blob/master/iPhone-Storyboard/Form.json), check the iPhone-Storyboard demo for more information,

**Comment by rene-dohan** [comment]
So how you create universal application, best way ? Isn't that what most people do ? You have to put there if device type check and create two jsons ? Or I can just use iphone json on ipad ? It's not much clear ? It's mentioned somewhere in doc ?

**Comment by 3lvis** [comment]
@rene-dohan We went for this approach since it gives the developers more control over the UI. You have to add a check for device and present the JSON file that matches the device.

I'll create a FAQ section in the README to document this, I'm sorry if this wasn't documented properly or it wasn't as obvious as I thought.

Let me know if I can help you with anything else :)

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/Form/pull/527
