### ISSUE TITLE
Feature Request: Allow custom input validator

### ISSUE THREAD

**Issue by aminiz** [hyperoslo/Form#569]
I would like to subclass FORMInputValidator.

This will give us a lot of flexibility. Initially, I need to use it to limit users to certain regex like one that would require a number with 2 decimal digits.

**Comment by 3lvis** [comment]
Hi @aminiz,

This should already be possible, gonna put an example.

**Comment by aminiz** [comment]
Thanks @3lvis 

All I really need is a pointer to get me started.

**Comment by 3lvis** [comment]
Damn, went on vacations and forgot about this. Sorry.

**Comment by aminiz** [comment]
@3lvis No worries! I can do any work required for this (be it making an example or implementing something) as long as I know what to do :)

**Comment by 3lvis** [comment]
OK! Got the time to add a demo for it, sadly it only works for Objective-C validators.

Form checks for the field id and looks for a validator for it. So if your field id is "External" it will look for FORMExternalValidator, then use that to validate the field.

I added a field with id "branded" for the demo.

https://github.com/hyperoslo/Form/tree/master/Basic-Swift

I hope this works for you, otherwise let me know.

**Comment by 3lvis** [comment]
A few validators to be used as examples.

https://github.com/hyperoslo/Form/tree/master/Source/Validators

**Comment by aminiz** [comment]
Thanks! I will try them now.

**Comment by aminiz** [comment]
Both FormValidator and FormInputValidator work like a charm!
