### ISSUE TITLE
Use case difference between Sections and Fields

### ISSUE THREAD

**Issue by jasper-ch-chan** [hyperoslo/Form#574]
Not an issue, but I am struggling to understand the use case difference between a Section and a Field. 

Assume I have a simple form of 2 text fields: First Name and Last Name. Suppose also I want the First Name cell to be on the top, and the Last Name cell to be directly below it.

Presently, you can implement the JSON as 1 section with 2 fields of 100% width each, or 2 sections with 1 field each.

Which is the most correct answer?

**Comment by 3lvis** [comment]
Hi @jasper-ch-chan,

A section groups a bunch of fields that represent the same category. For example, first name and last name belong to the category "Personal details" if you had a field called "Monthly salary" could go into "Contract details", etc.

The main difference is that Form takes your fields and groups them using a header:

![basic-form](https://user-images.githubusercontent.com/1088217/27241517-81225d4e-52d9-11e7-99cf-c87b7b87fee5.png)

**Comment by jasper-ch-chan** [comment]
Hi @3lvis 

Doesn't that sound like Groups then? So are you saying that section doesn't really play any real UI aspect to it, but rather its just a data container for fields?

**Comment by 3lvis** [comment]
@jasper-ch-chan My bad, was mistaking sections with groups, a section draws a separator line.

**Comment by jeffleeismyhero** [comment]
@jasper-ch-chan You might use a section when you don't want the fields to take up the full-width of the screen but still wish to start a new area for fields:

<img width="567" alt="form-section" src="https://user-images.githubusercontent.com/43980/27242580-891fa85c-52a3-11e7-816c-886d4a2ded0e.png">

Another benefit of putting fields into sections is that you can act on the entire section rather than each field individually. This can save a lot of time and code:

```objective-c
[FORMTarget hideSectionTargetWithID:@"development-section"];
```

**Comment by jasper-ch-chan** [comment]
@jeffleeismyhero @3lvis 
Thanks for your explanation. I see what the difference is between the two now.
